name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jonathanrogers/nestjsv2:${{ github.sha }}
          
          

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Deploy Stack
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |

              docker container stop $(docker ps | awk '/shiksha-backend/ {print $1}')
              
              docker system prune -a

              docker pull jonathanrogers/nestjsv2:${{ github.sha }}
         
              docker run -d --name shiksha-backend -p 9229:9229 -t jonathanrogers/nestjsv2:${{ github.sha }}
